### ISSUE TITLE
Printing doesn't seem to work

### ISSUE THREAD

**Issue by devogon** [wilrnh/emergencywalletcards.com#28]
On Linux (Fedora), using any of: Firefox, Brave, Vivaldi, clicking the print button does nothing at all.

**Comment by devogon** [comment]
Yeah, never mind. Using a not-USA formatted postal code prevents printing.

**Comment by devogon** [comment]
see above comment.

**Comment by wilrnh** [comment]
This seems like a terrible bug: nothing should prevent printing; aok if its printed and scrolls off the page, but it should always print, I think. Could you share what the not-USA formatted postal code was, and maybe reopen this if it still happens?
